# Change these first
owner: HCHS-CSDC # Your GitHub organization or username, where this repository lives
repo: CSDC-OJ-Uptime # The name of this repository

sites:
  - name: CSDC OJ
    url: https://csdc.tw

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /CSDC-OJ-Uptime
  logoUrl: https://avatars.githubusercontent.com/u/96825441
  name: 竹中軟研OJ狀態
  theme: night
  introTitle: "以下是目前竹中軟研OJ線上狀態"
  introMessage: 本服務由[upptime/upptime](https://github.com/upptime/upptime)所創建
  navbar:
    - title: Status
      href: /
    - title: GitHub Repository
      href: https://github.com/HCHS-CSDC/CSDC-OJ-Uptime
    - title: CSDC OJ
      href: https://csdc.tw
    - title: Facebook
      href: https://www.facebook.com/hchscsdc/
  favicon: https://avatars.githubusercontent.com/u/96825441
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
